/* This file is generated by mruby-mrbgems-template
   We recommend you don't touch this if you aren't familiar with C . */
/* Original from mruby-cli. (c) Terence Lee and Zachary Scott under MIT Lisence.
   ref: https://github.com/hone/mruby-cli/blob/master/mrblib/mruby-cli/setup.rb#L233 */
#include <stdlib.h>
#include <stdio.h>
#include <mruby.h>
#include <mruby/array.h>
#include <mruby/variable.h>
#include <mruby/error.h>

#include <orgf/file.h>

#include <time.h>

int
main(int argc, char *argv[])
{
  mrb_state *mrb = mrb_open();
  mrb_value ARGV = mrb_ary_new_capa(mrb, argc - 1);
  int i;
  int return_value;

  mrb_gv_set(mrb, mrb_intern_lit(mrb, "$0"), mrb_str_new_cstr(mrb, argv[0]));
  for (i = 1; i < argc; i++) {
    mrb_ary_push(mrb, ARGV, mrb_str_new_cstr(mrb, argv[i]));
  }
  mrb_define_global_const(mrb, "ARGV", ARGV);
  mrb_setup_filesystem(mrb);
  mrb_int random_seed = (mrb_int)time(NULL);
  mrb_funcall(mrb, mrb_obj_value(mrb->kernel_module), "srand", 1, mrb_fixnum_value(random_seed));
  mrb_funcall(mrb, mrb_obj_value(mrb->kernel_module), "require", 1, mrb_str_new_cstr(mrb, "Scripts/main"));
  return_value = EXIT_SUCCESS;
  if (mrb->exc) {
    mrb_funcall(mrb, mrb_obj_value(mrb->kernel_module), "msgbox_error", 1, mrb_obj_value(mrb->exc));
    mrb_print_error(mrb);
    return_value = EXIT_FAILURE;
  }
  mrb_close_filesystem(mrb);
  mrb_close(mrb);

  return return_value;
}
